### ISSUE TITLE
Can't apply global styles to <i-feather> component

### ISSUE THREAD

**Issue by TheLordDrake** [michaelbazos/angular-feather#22] opened 2019-08-28 16:06 UTC
Because the `<i-feather>` component applies default styling, you cannot apply a global style to icons. Styles have to be applied locally, which is redundant if attempting to provide common style details to all icons in the application. For example, if I want all icons to be 50x50, I must create a component level class for each component using an icon.

Is there a suggested work around for this?

**Comment by michaelbazos** [comment] 2019-09-01 13:57
@TheLordDrake 

It's possible to take precedence over the existing inline styles of <i-feather> with the `!important` keyword:

```css
i-feather {
  height: 50px !important;
  width: 50px !important;
}
```

Alternatively, since all svg elements of the library have the `feather` css class you can also do that:

```css
.feather {
  height: 50px;
  width: 50px;
}
```

The svg element is under i-feather and has no inline width or height on it, so in this case no need for `!important`.

In addition, svg elements also have an `feather-{name}` class, so you can target specific icons if you need:

```css
.feather {
  height: 50px;
  width: 50px;
}

.feather-heart {
  color: red;
}
```

Let me know if this answers your question.

**Comment by TheLordDrake** [comment] 2019-09-03 14:02
Use of `!important` would prevent making adjustments to individual icons as needed and should generally be avoided.

I did try the `.feather` class and had the same issue with it.

I wasn't aware of the `feather-{name}` classes, so as yet I haven't tried those.

I was able to get it working by wrapping the `<i-feather>` component in another local component and applying a global style to that component. These seems to be working and does allow local overrides if needed.

**Comment by michaelbazos** [comment] 2019-09-06 16:32
If you can reproduce the issue, using the `feather` class, I can take a look at it.

**Comment by TheLordDrake** [comment] 2019-09-06 17:43
I can no longer duplicate it. So either my memory has failed me or there was something with my configuration that has since changed. Either way I think it's safe to say this is a non issue now.

**Comment by michaelbazos** [comment] 2019-09-06 17:47
I tried as well using the `feather` class, and could not reproduce the issue. Therefore, I also think it's safe to close it now. Thanks for your quick follow-up 👍

**Closed by michaelbazos** 2019-09-06 17:47 UTC
