### ISSUE TITLE
Can't resize icons with v 5.3

### ISSUE THREAD

**Issue by Zerokk** [michaelbazos/angular-feather#11] opened 2018-11-13 11:44 UTC
I tried styling icons via CSS classes, just as in the README example, but icons won't resize; their parent container just get bigger, while the actual SVG image stays the same. 

This is happening in Firefox at least.

**Comment by michaelbazos** [comment] 2018-11-13 16:02
Thanks for reporting @Zerokk 

Seems I cannot reproduce the issue. Does the [demo](https://stackblitz.com/edit/angular-feather?file=app%2Fapp.component.html) work for you in Firefox ?
Is it possible to reproduce the issue in stackblitz ?

**Comment by michaelbazos** [comment] 2018-12-21 02:49
@Zerokk any update on this?

**Comment by michaelbazos** [comment] 2019-01-12 15:01
Closing as non reproducible

**Closed by michaelbazos** 2019-01-12 15:01 UTC
